### ISSUE TITLE
Atomic CSS generation proof of concept

### ISSUE THREAD

**Issue by syfxlin** [syfxlin/reve#8]
The stylis library can convert CSS into AST, so you can create a CSS Store to dynamically store each style definition. When the field name and field value are the same, use the same class. An example is as follows:

```typescript
export const container = styled.css`
  font-size: 32px;
  background-color: lightblue;
`;

<div className={container} />
```

Output:

```html
<div class="fs-32 bc-lightblue"></div>
```

```css
.fs-32 {
  font-size: 32px;
}

.bc-lightblue {
  background-color: lightblue;
}
```

CSS Store:

```json
{
  "font-size: 32px": "fs-32",
  "background-color: lightblue": "bc-lightblue",
}
```
